#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Does the script on ``$PATH`` run OUR code? A correct install can be bypassed.

WHY THIS EXISTS (incident 2026-07-22, reported by the ``dotfiles`` agent)
------------------------------------------------------------------------
That container had scitex-cards 0.17.5 correctly installed, and every version
check said so — including ``_install_probe.check_install_honest``, which
compares metadata against the code beside it and was entirely right. But
``bin/scitex-cards`` was a 224-byte shim importing ``scitex_todo._cli`` from
the superseded 0.13.5 distribution, because BOTH distributions declare console
scripts of the same names and the last install owns the name.

0.13.5 predates the SQLite backend, so it ignored ``SCITEX_CARDS_STORE_BACKEND``
and fell through YAML precedence to the BUNDLED EXAMPLE inside site-packages:
that agent read 17 fixture rows where the board held 2,308, and its writes
landed in a package file nothing reads and any reinstall erases. It went
unnoticed until someone noticed the row count was absurd.

NO VERSION STRING CAN SEE THIS, which is the whole point. The installed
distribution really is current, the metadata really does describe the code
beside it, and the import graph really does contain the right package. The only
thing wrong is which module the SCRIPT reaches for — so that is what this reads.

This lives beside ``_install_probe`` rather than inside it because the two
answer different questions with no shared state: that one reads ``.dist-info``
to ask "is the version true?", this one reads executables on ``PATH`` to ask
"is the install being bypassed?". Neither sees the other's failure class.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

#: Console scripts this package owns. Both names route to the same entry point;
#: ``scitex-todo`` is the compat alias kept for the pre-rename muscle memory.
OWNED_SCRIPTS = ("scitex-cards", "scitex-todo")

#: The module a correct console script must import from.
REQUIRED_IMPORT_ROOT = "scitex_cards"

#: The superseded package. A script importing THIS is the failure being detected.
SUPERSEDED_IMPORT_ROOT = "scitex_todo"


def _all_on_path(name: str) -> list[Path]:
    """EVERY executable ``name`` on ``PATH``, in resolution order — not just the first.

    ``shutil.which`` returns only the winner, and reporting only the winner is
    a silent narrowing of scope. The mechanism of this whole incident class is
    "several copies exist and the wrong one wins", so a shadowed script sitting
    one ``PATH`` change behind a healthy one is a loaded gun, not a clean bill
    of health — and a check that never mentions it has quietly stopped
    answering the question it was asked.

    Learned from the ``dotfiles`` agent (2026-07-22), who found their own
    divergence checker doing exactly this: it skipped every file with no
    counterpart on the live surface, then printed a confident total that read
    as complete coverage. 1,145 files across 24 hooks went uncounted and
    unmentioned. Their words: a check that quietly narrows its own scope and
    then prints a number is worse than no check, because the number gets
    repeated.
    """
    found: list[Path] = []
    seen: set[str] = set()
    for entry in os.environ.get("PATH", "").split(os.pathsep):
        if not entry:
            continue
        candidate = Path(entry) / name
        try:
            usable = candidate.is_file() and os.access(candidate, os.X_OK)
        except OSError:
            continue
        if not usable:
            continue
        key = str(candidate.resolve()) if candidate.exists() else str(candidate)
        if key in seen:
            # Same real file reached twice (symlink, bind mount, duplicate PATH
            # entry). One copy, listed once — inflating the count would make a
            # benign layout look like drift.
            continue
        seen.add(key)
        found.append(candidate)
    return found


def _script_import_root(path: Path) -> str | None:
    """The top-level module ``path``'s console script imports, if determinable.

    Console scripts generated by pip/setuptools are a few lines of readable
    Python; this reads the import line rather than executing anything.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    for raw in text.splitlines():
        line = raw.strip()
        for prefix in ("from ", "import "):
            if not line.startswith(prefix):
                continue
            root = line[len(prefix) :].split()[0].split(".")[0]
            if root in (REQUIRED_IMPORT_ROOT, SUPERSEDED_IMPORT_ROOT):
                return root
    return None


def _classify(copies: list[Path]) -> tuple[list[str], list[str], list[str]]:
    """Sort every copy into (shadowed, ours, indeterminate), each fully named."""
    shadowed: list[str] = []
    ours: list[str] = []
    indeterminate: list[str] = []
    for position, found in enumerate(copies):
        root = _script_import_root(found)
        # A copy that is not first on PATH does not run today. It is still
        # reported: "the wrong copy wins" is this incident's entire mechanism.
        rank = "runs" if position == 0 else f"shadowed at #{position + 1}"
        # ALWAYS name the target found, never just a verdict: this check exists
        # because a healthy-looking summary is exactly what hid the incident.
        if root == SUPERSEDED_IMPORT_ROOT:
            shadowed.append(f"{found} ({rank}) -> imports {root}")
        elif root == REQUIRED_IMPORT_ROOT:
            ours.append(f"{found} ({rank}) -> imports {root}")
        else:
            # Neither of ours. Reported, NOT passed over: an unreadable or
            # unrecognised script is an unanswered question, and answering it
            # "healthy" is how a check quietly stops checking.
            indeterminate.append(f"{found} ({rank}) -> import target undetermined")
    return shadowed, ours, indeterminate


def check_console_scripts_not_shadowed() -> dict[str, object]:
    """Health-doctor check: do our console scripts run OUR code?

    Returns the doctor's ``{ok, detail, hint}`` contract. Never raises.

    Complementary to ``_install_probe.check_install_honest``, not a superset:
    that one catches metadata outliving its code, this one catches a correct
    install being bypassed.

    NOT a failure when no script is found: this package is legitimately used as
    a library and through the MCP server, where nothing needs a script on
    ``$PATH``. "Absent" and "pointing at the wrong package" are different facts
    and only the latter is damage — but absence is still NAMED, never silently
    skipped (see :func:`_all_on_path`).
    """
    shadowed: list[str] = []
    ours: list[str] = []
    indeterminate: list[str] = []
    absent: list[str] = []
    for name in OWNED_SCRIPTS:
        copies = _all_on_path(name)
        if not copies:
            absent.append(name)
            continue
        found_shadowed, found_ours, found_unknown = _classify(copies)
        shadowed.extend(found_shadowed)
        ours.extend(found_ours)
        indeterminate.extend(found_unknown)

    # What was NOT examined, stated in every outcome below. A check that
    # reports only on what it looked at, and stays silent about the rest,
    # publishes a number that reads as complete coverage.
    scope = f" (not on PATH, unexamined: {', '.join(absent)})" if absent else ""

    if shadowed:
        return {
            "ok": False,
            "detail": (
                "console script(s) run the SUPERSEDED package: "
                + "; ".join(shadowed)
                + ". That code predates the SQLite store, so it ignores the "
                "backend selection and silently reads/writes a YAML file — "
                "typically the bundled example inside site-packages — while "
                "every version check reports a healthy, current install." + scope
            ),
            "hint": (
                "reinstall so this package owns the scripts again: "
                "`pip install --force-reinstall --no-deps scitex-cards`, then "
                "re-run this check. If it comes back, the stale script is in a "
                "container overlay upper, which permanently shadows the base "
                "image — delete it on the HOST, not through the mount, and "
                "restart."
            ),
        }
    if indeterminate:
        return {
            "ok": False,
            "detail": (
                "could not determine what console script(s) import: "
                + "; ".join(indeterminate)
                + ". Not proof of damage — but this check cannot vouch for a "
                "script it could not read, and reporting that as healthy is "
                "how the 2026-07-22 shim stayed invisible." + scope
            ),
            "hint": (
                "read the script yourself and confirm it imports "
                f"{REQUIRED_IMPORT_ROOT}; if it is a wrapper this check does "
                "not understand, teach it that shape rather than widening the "
                "pass condition."
            ),
        }
    if not ours:
        return {
            "ok": True,
            "detail": (
                "no scitex-cards console script on PATH — nothing to shadow "
                f"(library/MCP-only install; looked for: {', '.join(OWNED_SCRIPTS)})"
            ),
            "hint": None,
        }
    return {
        "ok": True,
        "detail": "console script(s) verified: " + "; ".join(ours) + scope,
        "hint": None,
    }


# EOF
